### PR TITLE
GCI Task - Updated Dependencies

### PR DESCRIPTION
**Pull request by Youngestdev**
This PR, is referenced from the [GCI Task](https://codein.withgoogle.com/dashboard/task-instances/5977084351479808/) . In this PR, I fixed the `package.json` error issue which is a missing comma, updated the dependencies and fix the dependencies vulnerability.

### CODE REVIEW

**Comment by divyanshkul** [comment]
Hey! Please don't mix multiple tasks. It would be your loss

**Comment by divyanshkul** [comment]
Hey @Youngestdev The task that you claimed only required you to run the project and not fix bugs or update the dependencies. Please be precise to what the task asks for. 
Now as you have done the work that is required for other tasks, you may go ahead and claim those tasks, [1](https://codein.withgoogle.com/dashboard/tasks/5681622880878592/) and [2](https://codein.withgoogle.com/dashboard/tasks/4901276983754752/) submit the same PR link in those tasks as well.

**Comment by divyanshkul** [comment]
Please make sure to follow what is required and not over-do the task. 
If this happens again, only one of your task will be accepted (even if you do work for 4 other task). Please follow along with the tasks. Welcome to Code-In :)

**Comment by Youngestdev** [comment]
Thanks then, my mistake!

**Pull request closed without merging**
