### PR TITLE
Sample Tests using Mocha and Chai

### PR DESCRIPTION
**Pull request by sidhyatikku**
### Setting up test environment for lead management server - JBoss Community
* I've setup sample tests in `app.test.js`
* I've uploaded screenshots below
* [Task Link](https://codein.withgoogle.com/dashboard/task-instances/5143926240444416/?sp-organization=5198161816584192&sp-is_beginner=False&sp-search=test)

screen shot 2018-11-15 at 3 02 41 pm
screen shot 2018-11-15 at 3 57 17 pm

### CODE REVIEW

**Comment by sidhyatikku** [comment]
@nikitadhiman can you help me with the reason why the build is failing? Though Travis is showing that tests are running but it is expecting something. 
screen shot 2018-11-15 at 3 41 11 pm

**Comment by sidhyatikku** [comment]
I'm not able to squash commits as there were conflicts and I'd to merge them.
PFA
screen shot 2018-11-15 at 3 46 27 pm

**Comment by nikitadhiman** [comment]
travis_wait will solve this issue. Also happens when npm install takes lot
of time....

**Comment by sidhyatikku** [comment]
@nikitadhiman it doesn't help. I had conflicts which I then merged and after merging I guess it doesn't show that commit.

**Comment by nikitadhiman** [comment]
Ideally,merged commits should be visible and for that reordering part
mentioned in the error, doing Git commit --amend and being satisfied with
changes Git rebase --continue would do the trick... It moves to each commit
one by one... Need to check why merge for you is an issue.

**Comment by sidhyatikku** [comment]
I'm getting the above option whenever I'm doing git rebase -i

**Comment by sidhyatikku** [comment]
@nikitadhiman I'm closing this PR and making a fresh new one.

**Pull request closed without merging**
