### PR TITLE
Bug fixed

### LINKED ISSUE #77: Incorrect path for angular CSS and scripts
When I started the server after running `npm install` and updating dependencies, I noticed that the UI looked as if there was no CSS applied.

It looked like this:
no-css

I realized that the console logged several error messages:
console
It seemed that the file paths were wrong or the files were non-existent.

After changing the file paths in `public/index.html`,the UI looked much nicer:
after-fixes

I'm not sure if this could have caused the issue, but
-  I did not configure Firebase
-  I am running node 10
-  I am not using HTTPS on localhost

### PR DESCRIPTION
**Pull request by NishSatish**
This commit should resolve #77 and also brings the project to life with its main functional buttons visible.

### CODE REVIEW

**Comment by junron** [comment]
Would be awesome if you could credit me for the fixes 😊

**Comment by nikitadhiman** [comment]
@junron fixed this first, thanks for your efforts too @NishSatish

**Comment by NishSatish** [comment]
I thank @junron for suggesting the changes. Sorry for not mentioning any credits. I did not see any pull request like this one merged so, I thought I was the first one! I referenced the issue though.

**Comment by nikitadhiman** [comment]
Closing this for now

**Pull request closed without merging**
